<?php

namespace App\Controller;

use App\Entity\Profilsecu;
use App\Form\ProfilsecuType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class SecurityController extends AbstractController
{
    /**
     * @Route("/login", name="app_login")
     */
    public function login(AuthenticationUtils $authenticationUtils): Response
    {

        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', [
            'last_username' => $lastUsername,
            'error' => $error
        ]);
    }

    /**
     * @Route("/connexion-inscription", name="connexion_inscription")
     */
    public function connexionInscription(Request $request, UserPasswordEncoderInterface $encoder)
    {

        /**
         * Fonction pour inscription
         */
        $user = new Profilsecu();

        $form = $this->createForm(ProfilsecuType::Class, $user, []);
        $form->handleRequest($request);

        if( $form->isSubmitted() && !$form->isEmpty() && $form->isValid()) {
            //Permet de rajouter un encodage au mdp
            $encrypted = $encoder->encodePassword($user, $user->getPasswordsecu());
            $user->setPasswordsecu($encrypted);

            if ($user->getImageprofil() != '' || $user->getImageprofil() != null) {
                //ajout d'une photo
                $file = $form->get('imageprofil')->getData();

                $fileName = $this->generateUniqueFileName() . '.' . $file->guessExtension();
                try {
                    $file->move(
                        $this->getParameter('profil_pictures_directory'),
                        $fileName
                    );
                } catch (FileException $e) {
                    $this->addFlash('error', 'Un problème est survenue sur votre photo lors de l\'enregistrement!');

                    return $this->redirectToRoute('home', []);
                }


            } else {
                $fileName = '';
            }


            $user->setImageprofil($fileName);
            $user->setStatut('0');

            $doctrine = $this->getDoctrine();
            $entityManager = $doctrine->getManager();
            $entityManager->persist($user);
            $entityManager->flush();

            $this->addFlash('success', 'Votre compte a bien été enregistré!');
            return $this->redirectToRoute('home',[]);
        }

        return $this->render('profil/connexioninscription.html.twig', [

            'formAjout' => $form->createView(),
         ]);

    }

    /**
     * @Route("/logout", name="app_logout")
     */
    public function logout()
    {
        return $this->redirectToRoute('home');
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}
